import { publicConfig } from "@/lib/config";

/**
 * FAQ content, defined once and rendered on both the landing page and /faq so
 * the two can never drift apart. The answers are also the source for the
 * FAQPage structured data, which means the marked-up answer is always the same
 * text a visitor reads.
 */

export interface FaqItem {
  question: string;
  answer: string;
}

export const FAQ: FaqItem[] = [
  {
    question: "Does AI Remove Pilot store my images?",
    answer:
      "No. Your image is held in memory only for as long as it takes to clean it, and the cleaned file is sent straight back as the response body. There is no upload directory, no object storage bucket, no database row and no download link that could be visited later. When the request ends, the image is gone from the server.",
  },
  {
    question: "Does this guarantee removal of Facebook's AI label?",
    answer:
      "No, and be sceptical of any tool that says otherwise. We remove metadata that is embedded in the file, including supported C2PA provenance manifests. Platforms can also apply an AI-generated label from signals that have nothing to do with your file's metadata — their own record of how the image was created, an account-level history, a partner's disclosure, or their own classifiers running on the pixels. Cleaning metadata cannot reach any of those.",
  },
  {
    question: "What metadata can be removed?",
    answer:
      "EXIF tag blocks, GPS and location records, camera and lens identification including serial numbers, software and editing-history fields, XMP packets, IPTC records, embedded thumbnails, free-text comment blocks (including the prompt dumps some generative tools write), and supported embedded provenance manifests such as C2PA Content Credentials. The report after cleaning is generated by re-reading the output file, so it reflects what is actually gone.",
  },
  {
    question: "Does image quality change?",
    answer:
      "Removing metadata means re-encoding the file, so it depends on the format. PNG and lossless WebP are re-encoded losslessly: the pixels are mathematically identical. JPEG and lossy WebP must be re-compressed, and we default to quality 92 with no chroma subsampling, which is visually equivalent to the original for practical purposes. We do not claim the JPEG result is bit-identical, because it isn't.",
  },
  {
    question: "Do I need an account?",
    answer:
      "No. The image-cleaning workflow has no sign-up, no login and no email capture. There is nothing to create an account for, since nothing is kept between visits.",
  },
  {
    question: "Are my images used to train AI?",
    answer:
      "No. Uploaded images are never used for model training, never sent to any third-party AI service, and never used for analytics. The processing is a local image-library operation on our own server — no external API sees your file.",
  },
  {
    question: "What file formats are supported?",
    answer:
      "JPG/JPEG, PNG and WebP, up to " +
      publicConfig.maxUploadMb +
      " MB. The processing layer is format-agnostic, so more can be added without changing the pipeline.",
  },
  {
    question: "Will the rotation of my photo change?",
    answer:
      "No. Photo orientation is stored as an EXIF tag rather than in the pixels, so naively stripping metadata is what makes a cleaned photo come back sideways. We apply the rotation to the pixels first, then discard the tag, so the image looks the same everywhere.",
  },
];
