import sharp from "sharp";

/**
 * Fixture builders.
 *
 * These produce real encoded images with real metadata rather than checked-in
 * binaries, so the suite tests the actual pipeline against files it generated
 * itself and nobody has to trust an opaque blob in the repository.
 */

const BASE = {
  create: {
    width: 240,
    height: 160,
    channels: 3 as const,
    background: { r: 60, g: 96, b: 160 },
  },
};

/** A JPEG carrying camera, software, timestamp and GPS tags. */
export async function jpegWithExif(): Promise<Buffer> {
  return sharp(BASE)
    .withExif({
      IFD0: {
        Make: "FixtureCam",
        Model: "FX-1",
        Software: "Fixture Suite 2.0",
        DateTime: "2026:01:02 03:04:05",
        Artist: "Fixture Author",
      },
      IFD2: {
        DateTimeOriginal: "2026:01:02 03:04:05",
        BodySerialNumber: "SN-0001",
        LensModel: "FX 24-70mm",
      },
      // sharp maps IFD3 to the GPS IFD.
      IFD3: {
        GPSLatitudeRef: "N",
        GPSLatitude: "51/1 30/1 0/1",
        GPSLongitudeRef: "W",
        GPSLongitude: "0/1 7/1 0/1",
      },
    })
    .jpeg({ quality: 90 })
    .toBuffer();
}

/** A clean JPEG with no auxiliary segments beyond what the encoder writes. */
export async function plainJpeg(width = 240, height = 160): Promise<Buffer> {
  return sharp({ ...BASE, create: { ...BASE.create, width, height } })
    .jpeg({ quality: 90 })
    .toBuffer();
}

export async function plainPng(): Promise<Buffer> {
  return sharp(BASE).png().toBuffer();
}

export async function plainWebp(): Promise<Buffer> {
  return sharp(BASE).webp({ quality: 90 }).toBuffer();
}

export async function losslessWebp(): Promise<Buffer> {
  return sharp(BASE).webp({ lossless: true }).toBuffer();
}

/** A PNG with an alpha channel, used to check transparency survives. */
export async function pngWithAlpha(): Promise<Buffer> {
  return sharp({
    create: {
      width: 120,
      height: 120,
      channels: 4,
      background: { r: 200, g: 40, b: 40, alpha: 0.5 },
    },
  })
    .png()
    .toBuffer();
}

/* ------------------------------------------------------------------ */
/* Byte-level surgery, for segments sharp will not write for us        */
/* ------------------------------------------------------------------ */

function asciiBytes(text: string): Buffer {
  return Buffer.from(text, "latin1");
}

/**
 * Insert a JPEG APPn segment immediately after the SOI marker.
 * `signature` is the segment's identifying prefix, e.g. the XMP namespace URI.
 */
export function insertJpegSegment(
  jpeg: Buffer,
  marker: number,
  signature: string,
  payload: string,
): Buffer {
  const body = Buffer.concat([asciiBytes(signature), asciiBytes(payload)]);
  const length = body.length + 2;
  const header = Buffer.from([0xff, marker, (length >> 8) & 0xff, length & 0xff]);
  return Buffer.concat([jpeg.subarray(0, 2), header, body, jpeg.subarray(2)]);
}

/** A JPEG carrying an XMP packet that declares generative-AI provenance. */
export function jpegWithAiXmp(jpeg: Buffer): Buffer {
  const xmp =
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>' +
    '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">' +
    '<rdf:Description xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" ' +
    'Iptc4xmpExt:DigitalSourceType="http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"/>' +
    '</rdf:RDF></x:xmpmeta><?xpacket end="w"?>';
  return insertJpegSegment(jpeg, 0xe1, "http://ns.adobe.com/xap/1.0/\0", xmp);
}

/** A JPEG carrying an APP11 JUMBF box, the container C2PA manifests use. */
export function jpegWithC2pa(jpeg: Buffer): Buffer {
  return insertJpegSegment(jpeg, 0xeb, "JP\0\0", "\0\0\0\x18jumbc2pa fixture manifest");
}

/** A JPEG carrying a free-text comment segment. */
export function jpegWithComment(jpeg: Buffer): Buffer {
  return insertJpegSegment(jpeg, 0xfe, "", "generated by a fixture");
}

/**
 * Append a PNG chunk before IEND. Used for text chunks and provenance boxes
 * that sharp has no API to write.
 */
export function insertPngChunk(png: Buffer, type: string, data: Buffer): Buffer {
  const iend = png.length - 12; // length + "IEND" + CRC
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const typeAndData = Buffer.concat([asciiBytes(type), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typeAndData), 0);
  return Buffer.concat([png.subarray(0, iend), length, typeAndData, crc, png.subarray(iend)]);
}

/** A PNG with a `tEXt` chunk whose keyword is a generative-tool parameter dump. */
export function pngWithAiText(png: Buffer): Buffer {
  return insertPngChunk(png, "tEXt", asciiBytes("parameters\0a fixture prompt, steps: 20"));
}

/** A PNG with a `tEXt` software tag. */
export function pngWithSoftware(png: Buffer): Buffer {
  return insertPngChunk(png, "tEXt", asciiBytes("Software\0Fixture Suite 2.0"));
}

/** A PNG with the C2PA-registered `caBX` chunk. */
export function pngWithC2pa(png: Buffer): Buffer {
  return insertPngChunk(png, "caBX", asciiBytes("jumbc2pa fixture manifest"));
}

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buffer: Buffer): number {
  let c = 0xffffffff;
  for (const byte of buffer) c = (CRC_TABLE[(c ^ byte) & 0xff] as number) ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
